[project]
name = "codedoctor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "paul1231231", email = "pokpokli557@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.143.0",
    "openai>=3.26.1",
    "pydantic>=2",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
codedoctor = "codedoctor:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
