[project]
name = "codedoctor"
version = "0.1.0"
description = "Code Doctor help programmer to identify they problem and solve it through AI"
readme = "README.md"
authors = [
    { name = "paul1231231", email = "pokpokli557@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.143.0",
    "guardrail-ai>=0.1.8",
    "guardrails-ai-detect-pii>=0.0.6",
    "guardrails-ai-prompt-injection-detector>=0.0.2",
    "litellm[proxy]>=1.83.0",
    "openai>=1.30.1,<3.0.0",
    "pydantic>=2",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
codedoctor = "codedoctor:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
